# Generated by Django for nabmqttd

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("broker_host", models.CharField(default="192.168.1.195", max_length=255)),
                ("broker_port", models.IntegerField(default=1883)),
                ("broker_username", models.CharField(blank=True, default="", max_length=255)),
                ("broker_password", models.CharField(blank=True, default="", max_length=255)),
                ("topic_prefix", models.CharField(default="nabaztag", max_length=255)),
                ("enabled", models.BooleanField(default=False)),
                ("publish_button_events", models.BooleanField(default=True)),
                ("publish_rfid_events", models.BooleanField(default=True)),
                ("publish_ears_state", models.BooleanField(default=True)),
                ("publish_led_state", models.BooleanField(default=True)),
                ("client_id", models.CharField(default="nabaztag_aaron", max_length=255)),
                ("json_data_base", models.TextField(null=True, default="{}")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
